#!/usr/bin/env node
/**
 * Regenerates docs-site/docs/benchmarks.md from a vitest bench JSON
 * report. Run through `npm run bench:report`, which runs the bench suite
 * with --reporter=json into bench-results.json first; this script turns
 * that report into the docs page and deletes the intermediate file.
 *
 * Numbers published on the docs page are always a full-suite run on the
 * machine that generated them — date, Node version and CPU are stamped
 * into the page so readers can tell snapshots apart.
 */
import {readFileSync, writeFileSync, rmSync, existsSync} from 'node:fs';
import {execSync} from 'node:child_process';
import {homedir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const reportPath = join(root, 'bench-results.json');

if (!existsSync(reportPath)) {
  console.error(
    'bench-results.json missing — run `npm run bench:report` (it runs the suite and passes the report in).'
  );
  process.exit(1);
}

const report = JSON.parse(readFileSync(reportPath, 'utf8'));

/** @type {{group: string; name: string; meanMs: number; rme: number}[]} */
const rows = [];
for (const file of report.testResults ?? []) {
  for (const group of file.assertionResults ?? []) {
    for (const bench of group.benchmarks ?? []) {
      for (const task of bench.tasks ?? []) {
        if (task.latency?.mean === undefined) continue;
        rows.push({
          group: bench.name,
          name: task.name,
          meanMs: task.latency.mean,
          rme: task.latency.rme
        });
      }
    }
  }
}

if (rows.length === 0) {
  console.error('No benchmark rows found in bench-results.json.');
  process.exit(1);
}

const cpu = (() => {
  try {
    const info = execSync('lscpu', {encoding: 'utf8'});
    const model = info.match(/Model name:\s*(.+)/)?.[1];
    return (model ?? 'unknown CPU').trim();
  } catch {
    return 'unknown CPU';
  }
})();

const nodeVersion = process.version;
const date = new Date().toISOString().slice(0, 10);
const user = (() => {
  try {
    return execSync('hostname', {encoding: 'utf8'}).trim();
  } catch {
    return homedir().split('/').pop() ?? 'unknown';
  }
})();

/** One significant figure at µs scale: 0.167ms -> 167µs, 25.7ms -> 25.7ms. */
function formatMean(meanMs) {
  if (meanMs < 1) return `${Math.round(meanMs * 1000)}µs`;
  if (meanMs < 10) return `${(meanMs * 1000).toFixed(0)}µs`;
  return `${meanMs.toFixed(1)}ms`;
}

const tableRows = rows
  .map(
    row =>
      `| ${row.group} — ${row.name} | ${formatMean(row.meanMs)} | ${row.meanMs > 0 ? Math.round(1000 / row.meanMs).toLocaleString('en-US') : '—'}/s | ${row.rme.toFixed(1)}% |`
  )
  .join('\n');

const page = `---
sidebar_position: 3
---

# Benchmarks

Generated by \`npm run bench:report\` — the full suite (\`test/bench/\`) in one run, every comparison row from the same process. Snapshot details:

- **Date**: ${date}
- **Machine**: ${user} (${cpu})
- **Node**: ${nodeVersion}

## Results

| Scenario | Mean | Throughput | RME |
|---|---|---|---|
${tableRows}

## CI regression bounds

The same suite runs in CI (\`.github/workflows/ci.yml\`, \`bench\` job) with
\`BENCH_ASSERT=1\`, which activates per-row bounds inline in the bench files.
The bounds carry ~5–8× headroom over local means deliberately: shared GitHub
runners are noisy, and the job exists to catch order-of-magnitude
regressions, not to race. Bounds (ms):

| Bound (ms) | Guards |
|---|---|
| 1.0 | f0rm \`Field\`: change re-renders 1 of 100 |
| 0.1 | f0rm \`Field uncontrolled\`: change 1 of 100; \`getValues + validate\` submit path |
| 5.0 | f0rm \`Field\`: change re-renders 1 of 1000 |
| 150 | async validation storm (3 changes × 50 debounced validators) |
| 40 | \`await trigger(form)\`: 50 sync + 50 async validators |
| 0.4 | \`getValues\` copy-on-write ownership merge |
| 0.3 | \`isDirty\` full scan |

## Reading the numbers

- The re-render count is asserted inline by the benches themselves: the
  100/1000-field rows throw if more than 1 of N fields re-renders per
  change, and the storm row throws unless debounce coalesces the 150-event
  burst into exactly 50 validator runs.
- Runs wobble between executions (µs-scale rows flip ±10% run to run) —
  compare ratios, not absolute values across snapshots.
- Competitor rows (react-hook-form, tanstack-react-form) run in the same
  process with the same tree shape; they have no CI bounds.

## Reproduce

\`\`\`sh
npm run bench:report           # full suite -> regenerates this page
npx vitest bench --run test/bench/   # interactive table only
\`\`\`
`;

writeFileSync(join(root, 'docs-site/docs/benchmarks.md'), page);
rmSync(reportPath);
console.log(`docs-site/docs/benchmarks.md regenerated (${rows.length} rows).`);
